sudo: required

language: java

services:

jdk:
- oraclejdk8

before_install:
- chmod +x pom.xml
- chmod +x deploy.sh

script:
- mvn test -Dtest=TestAlarm

after_success:
- mvn site
- mvn clean
- "./deploy.sh $GITHUB_TOKEN"
