sudo: required

language: java

services:

jdk:
- oraclejdk8

before_install:
- chmod +x pom.xml
- chmod +x deploy.sh

script:
- mvn test -Dtest=TestAlarm
- mvn site
- mvn clean

#- "./deploy.sh $GITHUB_TOKEN"

deploy:
  skip_cleanup: true
  provider: pages
  github-token: $GITHUB_TOKEN
  local_dir: docs/
  on:
    branch: travis-test  #temp for test
  keep-history: true  # creates incremental commits

env:
  global:
    secure: yejds3ymuIeK2iFGGuVQtrAT28PdseB2lVC6FFLbIWEL+F+zRPp8GczBCAKgJUj5PlZxUcBTx9azRnnlRx7b55v608DRTPU1IL06VFZbahaQOxlUHIt4Xtc0BlQVICBQ00BJdg92RtERgjP333LAay6r8fbmBPEmUxg3COo7HnY5ZSezyeKFdt9iQfJHvgyC5yufpuUgHY70Dkv950NPv6zsNOJTxm8RwCAVFOHLoXvEHjNjBfrQf9+vdmU6Mxl/AlQvQrrKRNS3abX5GfuKOonFHLAlLD0FqykHd6kmrjzvGh2MMf7ehytb1nSlcGCxIrvKmYgovbsMiU8HJUPHI9gvQx/yspJ7KFw6rHA6/3kXsC97ywiS7j77dHq/gePy/Merbtl48p5aiEBj70otSatKcVUKmrtsOipziISe6cwx2loh+RdiAe7k+Ksf9HG6OI0s8Rfetf+UJZR8hXf0DZU050zJ1RwpS8+dPCPtntlmyeIwJaO2qdPH8IWMjE2xErP2C8oW6gOvV+7+UXiHxr/CVI4a9CdfaV8cfx3xnjzZ7/TyIW4EWLqBx5r26F3q7ZE7ORAJIz8IuJ9VW8aFlsUHzXnZ1EoZeeOtPASMThJDYtKadxJZW14iWF5Ane2Eb4g8pYBHoirrYaZYRkCSj9ijeVZM6N6MTEsZJkuXFFI=
