sudo: required

language: java

services: 

dist:
  - xenial

packages:
  - oracle-java8-installer
  - oracle-java8-set-default

jdk:
  - oraclejdk8
  
before_install:
  - chmod +x pom.xml
  
script:
  - mvn test
